# Generated by Django 5.0.2 on 2024-09-16 04:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0001_initial"),
        ("user", "0005_alter_emailupdatecode_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="professionalservice",
            unique_together={("serivce", "professional")},
        ),
        migrations.RemoveField(
            model_name="professionalservice",
            name="serviceCatagory",
        ),
    ]
